export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";
export const GET_APP_STATUS = "GET_APP_STATUS";
export const SET_APP_STATUS = "SET_APP_STATUS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_LEVEL = "SET_CURRENT_LEVEL";
export const SET_LEVELS = "SET_LEVELS";
