// export const APP_ENV = "production";
export const APP_ENV = "debug";
export const APP_DEBUG_LEVEL = "debug";
export const API_BASE_URL = "http://mbj.test/api";
export const API_BASE_IMAGE_URL = "http://mbj.test";
// export const API_BASE_URL = "http://clients.responsive-pixel.com/mbj/public/api";
// export const API_BASE_IMAGE_URL = "http://clients.responsive-pixel.com/mbj/public";
// export const API_BASE_URL = "http://api.mybusinessjourney.com.au/api";
// export const API_BASE_IMAGE_URL = "http://api.mybusinessjourney.com.au";
